trigger:
  branches:
    include:
    - main # Reemplaza 'main' con el nombre de la rama principal de tu repositorio, si es diferente

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AWSShellScript@1
  inputs:
    awsCredentials: 'MyAWSServiceConnection' # Reemplaza esto con el nombre de tu conexión de servicio de AWS
    regionName: 'us-east-2' # Reemplaza esto con la región de tu bucket de S3
    scriptType: 'inline'
    inlineScript: |
      aws s3 sync . s3://s3andcloudfront-mybucketwebstaticproyectofinalmig-1wtdeqc95fze4 --delete --exclude ".git/*" --exclude "node_modules/*" --exclude "build/*"
  displayName: 'Sincronizar archivos del repositorio con el bucket de Amazon S3'

