# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

jobs:
- job: UploadToS3
  displayName: 'Upload files to Amazon S3'
  steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install awscli
    displayName: 'Install AWS CLI'

  - script: |
      aws s3 sync . s3://s3andcloudfront-mybucketwebstaticproyectofinalmig-1wtdeqc95fze4 --exclude ".git/*" --exclude ".gitignore" --exclude "azure-pipelines.yml"
    displayName: 'Upload files to Amazon S3'
